export const ADD_GAME = 'ADD_GAME';
export const SET_USER = "SET_USER";
export const DELETE_USER = "DELETE_USER";
export const AUTHENTICATED_SUCCESSFULLY = 'AUTHENTICATED_SUCCESSFULLY';
export const LOGOUT = 'LOGOUT';
